apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: {{ .Values.api.image }} #registry.srcmesh.dev/workshop/jerry:0.0.1 #python:latest
        env:
        - name: REDIS_HOST
          value: redis-svc
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 5000
        livenessProbe:
          tcpSocket: 
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1

      imagePullSecrets:
      - name: {{ .Values.registry.secretName }} #jerry-registry
---
apiVersion: v1
kind: Service
metadata:
  name: python-svc
spec:
  selector:
    app: python
  ports:
  - port: {{ .Values.api.svcPort }} #5000
    targetPort: 5000
  type: ClusterIP