apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: {{ .Values.redis.replicas }} #1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }} #redis:latest
        ports:
        - containerPort: 6379
        livenessProbe:
          exec:
            command:
            - redis-cli 
            - set
            - testkey
            - testvalue
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1



---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app: redis
  ports:
  - port: {{ .Values.redis.svcPort }} #6379
    targetPort: 6379
  type: ClusterIP